<?php

// Predefined suggestions based on resume titles
$predefinedSuggestions = [
    "Frontend Developer" => [
        "Skilled Frontend Developer with expertise in modern web technologies including React, HTML, CSS, and JavaScript, focused on building responsive and user-friendly web applications that deliver exceptional user experiences.",
        "Passionate Frontend Developer with a strong understanding of design principles, specializing in creating intuitive user interfaces and collaborating with designers and backend teams to develop seamless web applications.",
        "Innovative Frontend Developer with extensive experience in designing and implementing complex user-facing web applications, ensuring high performance and optimized user experience across all devices.",
        "Innovative Frontend Developer committed to implementing cutting-edge design systems and component libraries to streamline development processes and ensure consistent user interface across applications.",
        "Strategic Frontend Developer specializing in performance optimization, implementing advanced techniques like lazy loading, code splitting, and progressive web app technologies to enhance application speed and responsiveness.",
        "Proactive Frontend Developer skilled in accessibility design, ensuring web applications meet WCAG guidelines and provide inclusive user experiences for individuals with diverse abilities.",
        "Advanced Frontend Developer focused on implementing state management solutions using Redux, MobX, or Context API to create robust, scalable, and maintainable web application architectures.",
        "Performance-driven Frontend Developer experienced in implementing advanced rendering techniques like server-side rendering and static site generation to improve application load times and SEO.",
        "Security-conscious Frontend Developer specializing in implementing robust client-side security measures, protecting against XSS, CSRF, and other potential web vulnerabilities.",
        "Frontend Developer specializing in integrating advanced animation and interactive design techniques using CSS, SVG, and JavaScript libraries to create engaging user interfaces."

    ],
    "Backend Developer" => [
        "Experienced Backend Developer with proficiency in server-side languages such as Node.js, PHP, and Python, skilled at building secure, scalable, and high-performance applications for diverse business needs.",
        "Results-driven Backend Developer with expertise in building scalable and efficient web applications, leveraging the power of cloud technologies and RESTful APIs to enhance system functionality.",
        "Detail-oriented Backend Developer with a strong understanding of databases, cloud services, and APIs, dedicated to building maintainable and efficient backend systems that meet business objectives.",
        "Advanced Backend Developer focused on implementing microservices architecture, designing scalable and loosely coupled system components that enhance application flexibility and performance.",
        "Security-oriented Backend Developer specializing in implementing robust authentication, authorization, and encryption mechanisms to protect sensitive data and system integrity.",
        "Performance-driven Backend Developer experienced in optimizing database queries, implementing caching strategies, and designing efficient data retrieval mechanisms for high-load applications.",
        "Backend Developer with expertise in event-driven architectures, implementing message queues and asynchronous processing to enhance system responsiveness and scalability.",
        "Cloud-native Backend Developer proficient in designing serverless applications and implementing infrastructure as code using tools like AWS Lambda, Azure Functions, and Terraform.",
        "Compliance-focused Backend Developer skilled in implementing data protection regulations like GDPR, CCPA, and implementing robust data handling and privacy protection mechanisms.",
        "Performance monitoring Backend Developer experienced in implementing advanced logging, tracing, and system observability solutions to diagnose and resolve complex technical issues."

    ],
    "Full Stack Developer" => [
        "Versatile Full Stack Developer with expertise in both frontend and backend technologies like JavaScript, React, Node.js, and MongoDB, delivering robust and user-centric web applications for business solutions.",
        "Full Stack Developer with extensive experience building complete, end-to-end web applications, utilizing both frontend and backend technologies to create seamless integrations and enhanced system functionality.",
        "Experienced Full Stack Developer with proficiency in both client-side and server-side programming, creating dynamic, feature-rich websites that cater to diverse user needs and perform optimally.",
        "Innovative Full Stack Developer specializing in creating unified design systems that ensure consistent user experience across frontend and backend components.",
        "Security-conscious Full Stack Developer focused on implementing end-to-end security strategies, protecting applications from vulnerabilities at both client and server levels.",
        "Performance optimization Full Stack Developer skilled in implementing advanced caching mechanisms, database query optimization, and frontend rendering strategies.",
        "Accessibility-focused Full Stack Developer committed to creating inclusive web applications that meet WCAG guidelines and provide exceptional experiences for all users.",
        "Real-time collaboration Full Stack Developer specializing in implementing advanced synchronization and collaborative features across web and mobile platforms."
    ],
    "Project Manager" => [
        "Dynamic Project Manager with extensive experience in delivering complex projects on time and within budget, skilled in leading cross-functional teams and ensuring smooth project execution with a focus on quality.",
        "Skilled Project Manager with expertise in team collaboration, resource allocation, and successful project completion, adept at managing multiple projects concurrently while ensuring stakeholder satisfaction.",
        "Experienced Project Manager with a proven track record of leading high-impact projects, delivering results by effectively coordinating teams, managing budgets, and mitigating project risks.",
        "Dynamic Project Manager with extensive experience in delivering complex projects on time and within budget.",
        "Skilled in leading cross-functional teams and ensuring smooth project execution with a focus on quality.",
        "Proficient in risk assessment and mitigation strategies, ensuring project continuity and success.",
        "Experienced in Agile and Scrum methodologies, driving efficient and adaptable project workflows.",
        "Expert in stakeholder management, fostering clear communication and alignment with business goals.",
        "Strong background in resource allocation, optimizing team performance and project outcomes.",
        "Adept at using project management tools like Jira, Trello, and MS Project to streamline processes.",
        "Experienced in managing multiple concurrent projects while maintaining quality and deadlines.",
        "Focused on delivering innovative solutions that align with organizational objectives.",
        "Proven track record in budget management and cost control for large-scale projects.",
        "Skilled in vendor negotiation and contract management to optimize project resources.",
        "Experienced in training and mentoring junior project managers for organizational growth.",
        "Adept at crisis management and ensuring minimal disruption to project timelines.",
        "Proficient in developing detailed project plans and ensuring adherence at every phase.",
        "Strong understanding of compliance and regulatory requirements in project delivery.",
        "Focused on fostering a culture of accountability and excellence within project teams.",
        "Skilled in performance monitoring and reporting to ensure transparency and progress.",
        "Proven ability to deliver strategic initiatives that enhance organizational capabilities.",
        "Committed to continuous improvement and learning to drive project success.",
        "Dedicated to leveraging technology and innovation to optimize project outcomes."
    ],
    "Quality Assurance" => [
        "Detail-oriented Quality Assurance Engineer with experience in manual and automated testing, dedicated to ensuring the highest quality of software products through thorough testing, bug detection, and performance analysis.",
        "Skilled Quality Assurance professional specializing in testing methodologies, test automation, and performance analysis, focused on improving software functionality and ensuring bug-free releases.",
        "Experienced Quality Assurance Engineer with expertise in end-to-end testing processes, working closely with development teams to identify and resolve issues, ensuring seamless product performance across all platforms.",
        "Detail-oriented Quality Assurance Engineer with experience in manual and automated testing.",
        "Skilled in ensuring the highest quality of software products through thorough testing and analysis.",
        "Proficient in bug tracking tools like JIRA, Bugzilla, and TestRail for efficient issue management.",
        "Experienced in creating detailed test plans, cases, and scripts to ensure comprehensive coverage.",
        "Adept at performing regression, integration, and performance testing across various platforms.",
        "Strong background in using Selenium, Appium, and Postman for test automation.",
        "Focused on improving software functionality and ensuring seamless user experiences.",
        "Proficient in collaborating with development teams to identify and resolve issues effectively.",
        "Committed to maintaining rigorous documentation for all testing processes and outcomes.",
        "Adept at analyzing system requirements and developing efficient testing strategies.",
        "Skilled in API testing and validation using modern tools and frameworks.",
        "Experienced in load testing to ensure application scalability and reliability.",
        "Focused on reducing time-to-market through optimized testing workflows.",
        "Strong understanding of Agile and DevOps principles in testing environments.",
        "Proven track record of delivering bug-free releases in high-pressure deadlines.",
        "Experienced in conducting usability testing to enhance application user-friendliness.",
        "Proficient in cross-browser and cross-device compatibility testing.",
        "Dedicated to staying updated with the latest testing tools and technologies.",
        "Strong analytical skills to identify root causes and ensure long-term solutions.",
        "Committed to fostering a culture of quality assurance within development teams."
    ],
    "Devops Engineer" => [
        "Experienced DevOps Engineer with expertise in automation, continuous integration, and continuous delivery (CI/CD) pipelines, focused on streamlining development processes and enhancing collaboration between development and operations teams.",
        "Skilled DevOps Engineer with a solid understanding of cloud infrastructure, containerization, and orchestration tools like Docker and Kubernetes, optimizing deployment pipelines for faster and more reliable software releases.",
        "Proficient DevOps Engineer with experience in designing, implementing, and managing automated infrastructure and deployment solutions, ensuring scalability, reliability, and performance for web applications in the cloud.",
        "Experienced DevOps Engineer with expertise in automation and CI/CD pipelines.",
        "Proficient in tools like Jenkins, GitLab, and Azure DevOps for seamless deployment workflows.",
        "Skilled in cloud infrastructure management with AWS, Azure, and Google Cloud.",
        "Experienced in containerization and orchestration using Docker and Kubernetes.",
        "Adept at designing scalable and secure deployment solutions for enterprise applications.",
        "Focused on enhancing collaboration between development and operations teams.",
        "Experienced in implementing infrastructure as code (IaC) using Terraform and Ansible.",
        "Proficient in monitoring and logging tools like Prometheus, Grafana, and ELK stack.",
        "Dedicated to optimizing system performance and reducing deployment times.",
        "Skilled in designing robust disaster recovery and backup solutions.",
        "Experienced in automating testing and deployment processes for faster releases.",
        "Strong background in version control systems like Git and SVN.",
        "Proficient in scripting languages like Python, Bash, and PowerShell for automation tasks.",
        "Experienced in managing microservices architecture for scalable applications.",
        "Focused on ensuring security and compliance in deployment pipelines.",
        "Skilled in cost optimization for cloud-based infrastructure.",
        "Experienced in troubleshooting and resolving infrastructure issues promptly.",
        "Proficient in load balancing and high-availability configurations.",
        "Focused on continuous improvement and adopting best practices in DevOps.",
        "Committed to fostering a culture of innovation and efficiency within teams."
    ],
    "React Developer" => [
        "React Developer with a strong passion for building dynamic and interactive web applications using React.js, ensuring high performance, responsiveness, and scalability to meet the needs of users and businesses.",
        "Skilled React Developer focused on building fast, efficient, and modular user interfaces with React.js, integrating APIs, and ensuring seamless interaction across all platforms for a smooth user experience.",
        "Experienced React Developer with expertise in creating scalable, high-performance applications using React.js, building reusable components, and optimizing front-end performance for improved user experiences.",
        "React Developer with a passion for building interactive web applications.",
        "Experienced in creating scalable applications using React.js and Redux.",
        "Skilled in building reusable components for modular application development.",
        "Focused on optimizing application performance and responsiveness.",
        "Proficient in integrating REST APIs and GraphQL into React applications.",
        "Experienced in using state management libraries like MobX and Context API.",
        "Adept at implementing responsive design principles for cross-device compatibility.",
        "Skilled in leveraging modern JavaScript features like ES6+ for efficient coding.",
        "Experienced in testing React applications using tools like Jest and Enzyme.",
        "Proficient in collaborating with backend teams to ensure seamless integrations.",
        "Focused on improving user experience through intuitive UI designs.",
        "Skilled in debugging and troubleshooting React applications for smoother performance.",
        "Experienced in code versioning tools like Git for collaborative development.",
        "Dedicated to staying updated with the latest trends and technologies in React.",
        "Adept at developing Progressive Web Applications (PWAs) with React.",
        "Proficient in using tools like Webpack and Babel for build optimization.",
        "Focused on writing clean, maintainable, and scalable code.",
        "Experienced in implementing authentication and authorization features.",
        "Skilled in developing custom hooks to improve code reusability.",
        "Committed to delivering high-quality applications that meet user needs."
    ],
    "Web Developer" => [
        "Skilled Web Developer with a strong foundation in frontend and backend technologies, including HTML, CSS, JavaScript, and PHP, passionate about creating responsive and interactive websites that deliver great user experiences.",
        "Experienced Web Developer focused on creating functional, user-friendly websites with expertise in both frontend and backend technologies, ensuring smooth performance and seamless integration across platforms.",
        "Proficient Web Developer with a strong understanding of web technologies, UI/UX principles, and optimization techniques, delivering high-quality websites that engage users and meet business goals.",
        "Skilled Web Developer with a foundation in frontend and backend technologies.",
        "Experienced in creating responsive websites using HTML, CSS, and JavaScript.",
        "Adept at developing dynamic websites with PHP and MySQL.",
        "Focused on delivering interactive and user-friendly web applications.",
        "Experienced in using frameworks like Bootstrap and Tailwind CSS for design.",
        "Skilled in optimizing websites for speed and performance.",
        "Proficient in integrating third-party APIs into web applications.",
        "Experienced in using CMS platforms like WordPress and Joomla for development.",
        "Adept at implementing SEO best practices to enhance website visibility.",
        "Focused on cross-browser and cross-device compatibility.",
        "Proficient in deploying websites on hosting platforms like AWS and Heroku.",
        "Experienced in using Git for version control and collaborative development.",
        "Skilled in creating single-page applications (SPAs) using modern frameworks.",
        "Dedicated to ensuring website accessibility for all users.",
        "Adept at designing intuitive user interfaces for seamless navigation.",
        "Focused on maintaining website security through secure coding practices.",
        "Experienced in testing and debugging websites to ensure smooth functionality.",
        "Proficient in implementing payment gateways and eCommerce features.",
        "Skilled in analyzing user feedback to improve website features.",
        "Committed to staying updated with the latest web development trends.",
        "Highly skilled Web Developer with a comprehensive understanding of both front-end and back-end development, adept at creating responsive and visually appealing websites using modern web technologies including HTML5, CSS3, JavaScript, and frameworks like React and Angular. Proficient in integrating APIs and ensuring cross-browser compatibility to deliver seamless user experiences.",
        "Experienced Web Developer with a strong focus on creating scalable, high-performance web applications using technologies such as Node.js, Express, and MongoDB. Demonstrates expertise in implementing RESTful APIs, optimizing website performance, and adhering to best coding practices for maintainability and scalability.",
        "Proficient Web Developer with expertise in designing and deploying interactive web applications, leveraging advanced skills in PHP, Python, and SQL databases to create dynamic content-driven sites. Skilled in implementing robust security measures and optimizing database queries for enhanced performance.",
        "Dedicated Web Developer with a proven ability to manage the complete website development lifecycle, from concept and wireframing to deployment and maintenance. Specializes in building user-centric designs with a focus on accessibility, responsiveness, and SEO optimization to maximize reach and user engagement.",
        "Detail-oriented Web Developer with extensive experience in utilizing modern frameworks and libraries such as Vue.js and SASS to deliver feature-rich web solutions. Adept at employing Agile methodologies to ensure timely project delivery and alignment with client objectives.",
        "Innovative Web Developer with a passion for creating state-of-the-art websites and web applications. Expert in CMS platforms such as WordPress and Drupal, with a track record of customizing themes, plugins, and functionalities to meet diverse business needs.",
        "Results-driven Web Developer with deep expertise in eCommerce development, specializing in integrating payment gateways, building secure checkout systems, and optimizing user journeys to boost conversion rates. Proficient in Shopify, Magento, and WooCommerce platforms.",
        "Seasoned Web Developer with significant experience in cloud-based deployments and DevOps practices. Skilled in configuring CI/CD pipelines and leveraging AWS, Azure, or Google Cloud to deploy scalable, resilient web applications.",
        "Dynamic Web Developer with a knack for problem-solving and debugging, ensuring high-quality deliverables. Experienced in using testing frameworks like Jasmine, Mocha, and Selenium to guarantee bug-free applications that exceed user expectations.",
        "Strategic Web Developer committed to continuous improvement and staying abreast of industry trends. Skilled in developing Progressive Web Applications (PWAs) that provide app-like experiences and offline capabilities to users.",
        "Analytical Web Developer with extensive experience in big data integration and visualization, leveraging libraries like D3.js and Highcharts to create interactive dashboards and data-driven applications that empower business decision-making.",
        "Dedicated Web Developer focused on creating inclusive and accessible websites compliant with WCAG and ADA standards. Demonstrates a commitment to ensuring usability for all users, including those with disabilities, through meticulous design and testing."

    ],
    "Cloud Engineer" => [
        "Cloud Engineer with expertise in designing, implementing, and managing scalable cloud solutions, optimizing infrastructure on platforms like AWS, Azure, and Google Cloud to ensure high performance and security.",
        "Skilled Cloud Engineer with experience in cloud infrastructure management, automation, and security, helping businesses leverage the cloud for scalable, efficient, and cost-effective solutions.",
        "Experienced Cloud Engineer with a focus on cloud architecture, infrastructure as code, and automation, delivering robust and secure cloud solutions that enable businesses to scale seamlessly.",
        "Proficient Cloud Engineer with a strong understanding of cloud computing principles, cloud security, and compliance.",
        "Experienced in designing and implementing cloud-based infrastructure for scalable applications.",
        "Adept at managing cloud resources, including compute, storage, and networking.",
        "Focused on ensuring high availability and disaster recovery in cloud environments.",
        "Experienced in implementing cloud security best practices to protect data and applications.",
        "Skilled in using cloud management tools like Terraform and CloudFormation.",
        "Proficient in deploying and managing containerized applications on Kubernetes.",
        "Experienced in using cloud-based services like AWS Lambda and Azure Functions."

    ],
    "Engineering Manager" => [
        "Engineering Manager with a strong track record of leading engineering teams, driving innovation, and managing the development of high-quality software products while fostering a culture of collaboration and continuous improvement.",
        "Experienced Engineering Manager with expertise in guiding cross-functional teams, ensuring on-time project delivery, and implementing best practices for software development, quality assurance, and performance optimization.",
        "Dynamic Engineering Manager with extensive experience in managing engineering teams, defining technical strategies, and ensuring the successful delivery of large-scale software solutions while optimizing team performance."
    ],
    "SEO" => [
        "SEO Specialist with a proven track record of improving website rankings and driving organic traffic, utilizing advanced strategies in keyword research, content optimization, and technical SEO to boost search engine visibility.",
        "Experienced SEO professional with a deep understanding of search engine algorithms and ranking factors, dedicated to enhancing website performance and visibility through data-driven SEO strategies and content optimization.",
        "Skilled SEO expert with expertise in on-page and off-page optimization, content strategy, and link building, driving measurable improvements in organic traffic and search engine rankings for various websites.",
        "Results-driven SEO Specialist with expertise in on-page, off-page, and technical SEO, dedicated to improving website rankings and driving sustainable organic growth.",
        "Experienced in utilizing advanced keyword research tools like SEMrush and Ahrefs to identify opportunities and create impactful SEO strategies.",
        "Proficient in conducting comprehensive website audits to identify technical issues and optimize site architecture for improved crawlability and indexing.",
        "Specialist in local SEO, optimizing Google My Business profiles and managing location-based strategies to drive traffic and conversions for businesses.",
        "Adept at link-building strategies and outreach campaigns to enhance domain authority and search engine rankings.",
        "Skilled in content optimization and working closely with content teams to create SEO-friendly blogs, articles, and landing pages that align with search intent.",
        "Experienced in leveraging analytics tools like Google Analytics and Search Console to track SEO performance and refine strategies for maximum ROI.",
        "Focused on implementing schema markup, enhancing search visibility with rich snippets, and improving CTR for key landing pages.",
        "Proficient in optimizing eCommerce websites for product search, ensuring higher visibility and conversions through SEO techniques.",
        "Committed to staying updated with the latest search engine algorithm changes and evolving SEO trends to maintain competitive advantages."
    ],
    "SEO Specialist" => [
        "SEO Specialist with a proven track record of improving website rankings and driving organic traffic, utilizing advanced strategies in keyword research, content optimization, and technical SEO to boost search engine visibility.",
        "Experienced SEO professional with a deep understanding of search engine algorithms and ranking factors, dedicated to enhancing website performance and visibility through data-driven SEO strategies and content optimization.",
        "Skilled SEO expert with expertise in on-page and off-page optimization, content strategy, and link building, driving measurable improvements in organic traffic and search engine rankings for various websites.",
        "Results-driven SEO Specialist with expertise in on-page, off-page, and technical SEO, dedicated to improving website rankings and driving sustainable organic growth.",
        "Experienced in utilizing advanced keyword research tools like SEMrush and Ahrefs to identify opportunities and create impactful SEO strategies.",
        "Proficient in conducting comprehensive website audits to identify technical issues and optimize site architecture for improved crawlability and indexing.",
        "Specialist in local SEO, optimizing Google My Business profiles and managing location-based strategies to drive traffic and conversions for businesses.",
        "Adept at link-building strategies and outreach campaigns to enhance domain authority and search engine rankings.",
        "Skilled in content optimization and working closely with content teams to create SEO-friendly blogs, articles, and landing pages that align with search intent.",
        "Experienced in leveraging analytics tools like Google Analytics and Search Console to track SEO performance and refine strategies for maximum ROI.",
        "Focused on implementing schema markup, enhancing search visibility with rich snippets, and improving CTR for key landing pages.",
        "Proficient in optimizing eCommerce websites for product search, ensuring higher visibility and conversions through SEO techniques.",
        "Committed to staying updated with the latest search engine algorithm changes and evolving SEO trends to maintain competitive advantages."
    ],
    "Digital Marketer" => [
        "Results-oriented Digital Marketer with expertise in social media marketing, paid advertising, content marketing, and SEO, focused on driving brand growth and generating leads through innovative and effective campaigns.",
        "Skilled Digital Marketing Specialist with experience in developing and executing data-driven marketing strategies across various digital channels, driving traffic, engagement, and conversions for brands in diverse industries.",
        "Experienced Digital Marketer with a deep understanding of consumer behavior, digital marketing tools, and analytics, helping businesses increase brand awareness, customer engagement, and ROI through targeted online campaigns.",
        "Strategic Digital Marketer with a proven track record of planning and executing innovative campaigns that boost brand awareness, lead generation, and customer engagement.",
        "Experienced in developing data-driven strategies across multiple digital platforms, including social media, paid search, email marketing, and SEO.",
        "Proficient in managing PPC campaigns on platforms like Google Ads and Facebook Ads, optimizing budgets for maximum ROI.",
        "Adept at creating engaging content marketing strategies to drive audience engagement, improve brand positioning, and generate leads.",
        "Skilled in social media marketing, leveraging platforms like Instagram, LinkedIn, and TikTok to expand audience reach and drive targeted traffic.",
        "Experienced in designing and executing email marketing campaigns using tools like Mailchimp and HubSpot, achieving higher open and conversion rates.",
        "Proficient in web analytics tools like Google Analytics, Mixpanel, and Hotjar to monitor and optimize campaign performance.",
        "Focused on improving user experiences and conversion rates through A/B testing, landing page optimization, and personalized marketing strategies.",
        "Specialist in crafting multi-channel digital marketing campaigns that align with business objectives and deliver measurable results.",
        "Dedicated to utilizing emerging technologies, such as AI and automation tools, to streamline marketing efforts and enhance campaign efficiency."
    ],
    "JAVA Developer" => [
        "Skilled JAVA Developer with extensive experience in building enterprise-level applications, using technologies like Spring, Hibernate, and REST APIs to develop robust, scalable, and high-performance software solutions.",
        "Experienced JAVA Developer focused on creating secure, maintainable, and high-quality code, leveraging the power of Java to build enterprise applications that meet business requirements and enhance performance.",
        "Proficient JAVA Developer with a deep understanding of object-oriented programming principles, designing and developing scalable applications that deliver optimal functionality and performance in business environments.",
        "Innovative JAVA Developer with expertise in microservices architecture, leveraging frameworks like Spring Boot and Hibernate to create scalable and efficient enterprise-level solutions.",
        "Experienced JAVA Developer proficient in designing secure APIs and integrating them with front-end applications for seamless user experiences.",
        "Skilled JAVA Developer with a proven ability to optimize database queries and application performance for high-traffic environments.",
        "Proficient in Java-based distributed systems, with hands-on experience in implementing messaging systems using Kafka and RabbitMQ.",
        "Dynamic JAVA Developer focused on building real-time, data-intensive applications with robust back-end architectures.",
        "Adept JAVA Developer with a strong focus on implementing best practices in clean code and design patterns to deliver maintainable solutions.",
        "Experienced in deploying Java applications on cloud platforms like AWS and Azure, ensuring scalability and reliability.",
        "Skilled in implementing CI/CD pipelines for JAVA projects, streamlining deployment workflows and reducing release cycles.",
        "Specialist in multi-threading and concurrency in Java applications, ensuring optimal performance in complex systems.",
        "Committed to integrating testing frameworks like JUnit and TestNG to enhance application stability and reliability."
    ],
    "Dot Net Developer" => [
        "Skilled .NET Developer with a strong foundation in developing scalable and efficient web applications using C#, ASP.NET, and Microsoft SQL Server, focused on delivering high-quality solutions that meet business needs.",
        "Experienced .NET Developer with a focus on building dynamic and secure applications using the .NET framework, integrating third-party APIs, and ensuring optimized performance and user experience.",
        "Proficient .NET Developer with expertise in developing web and desktop applications, leveraging the full potential of the .NET ecosystem to build reliable and scalable software solutions.",
        "Highly skilled .NET Developer with expertise in building dynamic web applications using ASP.NET Core and Entity Framework.",
        "Experienced in designing secure and scalable APIs using .NET technologies to support modern business applications.",
        "Proficient in developing cloud-native applications using Azure App Services, ensuring seamless scalability and performance.",
        "Specialist in building enterprise solutions using .NET frameworks, WCF, and Web API for high-performing business systems.",
        "Adept at integrating third-party services and tools into .NET applications, enhancing functionality and user experience.",
        "Experienced in optimizing database operations with Entity Framework and LINQ, ensuring high-speed application performance.",
        "Skilled in implementing DevOps practices in .NET environments, leveraging tools like Azure DevOps and Jenkins for CI/CD pipelines.",
        "Focused on enhancing the reliability of applications by implementing robust testing practices using NUnit and MSTest.",
        "Dedicated to creating visually appealing and functional web applications by integrating front-end frameworks like Angular and React with .NET backends.",
        "Committed to delivering clean, maintainable, and reusable code in .NET projects by adhering to SOLID principles and design patterns."
    ],
    "Android Developer" => [
        "Experienced Android Developer with a strong background in building high-quality, scalable Android applications using Java and Kotlin, focused on delivering seamless user experiences and optimized performance.",
        "Skilled Android Developer with expertise in mobile development, designing and building feature-rich Android apps that provide exceptional performance and smooth functionality across all devices.",
        "Proficient Android Developer with a deep understanding of Android SDK, Java, and Kotlin, working on developing and maintaining mobile applications that meet the demands of users and businesses."
    ],
    "App Developer" => [
        "Skilled App Developer with expertise in developing mobile applications for both iOS and Android, focusing on user experience, performance, and security to deliver seamless mobile experiences.",
        "Experienced App Developer proficient in designing and building cross-platform applications, ensuring high-quality performance and optimized code for smooth functioning across a wide range of devices.",
        "Passionate App Developer focused on building scalable and responsive mobile apps that meet business requirements, leveraging tools like React Native and Flutter to create versatile mobile experiences.",
        "Passionate App Developer focused on delivering innovative and intuitive mobile applications for Android and iOS platforms, ensuring a seamless user experience.",
        "Experienced in building hybrid mobile applications using frameworks like React Native and Flutter to cater to diverse device ecosystems.",
        "Proficient in designing high-performance apps with a focus on UI/UX, security, and cross-platform compatibility.",
        "Dedicated to delivering data-driven mobile solutions by integrating RESTful APIs and third-party services into applications.",
        "Expertise in mobile app lifecycle management, from ideation to publishing on platforms like Google Play Store and Apple App Store.",
        "Adept at leveraging mobile app analytics tools like Firebase and Flurry to optimize performance and user engagement.",
        "Skilled in integrating real-time features such as push notifications, live updates, and geolocation in mobile applications.",
        "Proficient in creating offline-first mobile apps using local databases like SQLite and Room for a seamless user experience.",
        "Focused on optimizing app code for battery consumption and device performance, ensuring smooth functionality.",
        "Committed to staying ahead in mobile development trends by mastering AR/VR integration and AI-based features."

    ]
];


// Get the title from the query string
$title = isset($_GET['title']) ? $_GET['title'] : '';

// Return suggestions for the specified title
$suggestions = isset($predefinedSuggestions[$title]) ? $predefinedSuggestions[$title] : [];

// Return suggestions as JSON response
echo json_encode(['suggestions' => $suggestions]);

?>
